### ISSUE TITLE
Scrolling causes output corruption

### ISSUE THREAD

**Issue by Ptark** [kharvd/gpt-cli#18]
When I try to scroll back, the same few lines repeat over and over. This happens in multiple terminal emulators. Do you have any idea what could cause this?

**Comment by KaueSabinoSRV17** [comment]
Sometimes i see the same thing on my machine. I noticed, at least in my case, that the issue happens when the model is outputting a very large chunk of code.

While the issue is not fixed, my sugestion is to not change windows when the model is still outputting code. The more you scroll and change windows, the more it is gonna repeat the same lines
(given i work with 2 monitors, it is kinda not that big of a trouble, but i understand it must be bad using only one screen).

**Comment by kharvd** [comment]
Should be fixed now in `--no_markdown` mode. Might be harder to fix with the markdown

**Comment by williamjameshandley** [comment]
[sgpt](https://github.com/TheR1D/shell_gpt) fixes this by producing one screen of markdown formatted text, having three dots to it is still outputting and then pausing until the full ouput is produced:

Here are some screenshots (prompt: "write me ten functions in python for processing prime numbers")
with three dots:
![2025-01-01-174726_1920x1080_scrot](https://github.com/user-attachments/assets/803027f3-9bdb-4e5e-9b5b-773f286f994c)
and then the full output when done:
![2025-01-01-174735_1920x1080_scrot](https://github.com/user-attachments/assets/9e33618a-4100-41d2-88f6-eec9359e6e59)

This is a nice compromise, since it produces a full markdown formatted output, whilst allowing users to inspect the initial output to check if it's doing the right thing. How difficult would it be to adapt gpt-cli to have a similar output?
